### ISSUE TITLE
How can I use this robot4chat?

### ISSUE THREAD

**Issue by rachelxj** [palmtoy/robot4chat#1]
Hi, I have problem when I start running robot4chat with latest chatofpomelo, I got this exception below:
Any idea about this exception?
Started HTTP server on localhost:8889.
[Wed Apr 01 2015 10:23:26] INFO: Registering new web_client
 Caught exception: TypeError: object is not a function
    at Object.Server.announce_web_client (E:\study\pomelo\robot4chat-master\lib\
master\server.js:97:9)
    at Socket.<anonymous> (E:\study\pomelo\robot4chat-master\lib\master\server.j
s:132:25)
    at Socket.emit [as $emit](events.js:92:17)
    at SocketNamespace.handlePacket (E:\study\pomelo\robot4chat-master\node_modu
les\socket.io\lib\namespace.js:335:22)
    at Manager.onClientMessage (E:\study\pomelo\robot4chat-master\node_modules\s
ocket.io\lib\manager.js:469:38)
    at WebSocket.Transport.onMessage (E:\study\pomelo\robot4chat-master\node_mod
ules\socket.io\lib\transport.js:387:20)
    at Parser.<anonymous> (E:\study\pomelo\robot4chat-master\node_modules\socket
.io\lib\transports\websocket\hybi-16.js:39:10)
    at Parser.emit (events.js:95:17)
    at finish (E:\study\pomelo\robot4chat-master\node_modules\socket.io\lib\tran
sports\websocket\hybi-16.js:288:16)
    at Parser.expectHandler (E:\study\pomelo\robot4chat-master\node_modules\sock
et.io\lib\transports\websocket\hybi-16.js:299:15)

**Comment by rachelxj** [comment]
I tried to upgrade understore to 1.8.2, I still get errors
